### ISSUE TITLE
ec2-create-instance.sh for dataverse-kubernetes

### ISSUE THREAD

**Issue by pdurbin** [GlobalDataverseCommunityConsortium/dataverse-kubernetes#127]
There's a script called `ec2-create-instance.sh` mentioned in https://github.com/IQSS/dataverse-sample-data that I use all the time. Actually, https://jenkins.dataverse.org uses it all the time too. It's the basis for our automated testing strategy.

The most important thing about `ec2-create-instance.sh` is that it is a single script.

The second most important thing about `ec2-create-instance.sh` is that it supports AWS, which happens to be the cloud we are encouraged to use at Harvard. We document how to set up AWS credentials at http://guides.dataverse.org/en/4.18.1/developers/deployment.html#deploying-dataverse-to-amazon-web-services-aws

Would it be possible to create a script like this for dataverse-kubernetes?

**Comment by pdurbin** [comment]
The third most important thing about `ec2-create-instance.sh` is that it allows developers to spin up Dataverse based on any branch of any fork.

This is on my mind because I'm looking at (and just left a review on) https://github.com/IQSS/dataverse/pull/6490 which is from https://github.com/TexasDigitalLibrary/dataverse/tree/IQSS/6489 (the branch is "IQSS/6489"). Lots of changes to S3 support and storage options (in a good way, assuming it all works). 😄

**Comment by poikilotherm** [comment]
I'm pretty sure the refactored dev guide will be helpfull here.
https://dataverse-k8s.readthedocs.io/en/latest/development/index.html

This might be backed into a script.

**Comment by poikilotherm** [comment]
Had a brief talk at lunch of European Dataverse Workshop 2020 with @4tikhonov about a similar idea from him. I suggested to create some kind of generator, that is able to kustomize the K8s objects to your necessities and gives you a nice skeleton to start with.

**Comment by poikilotherm** [comment]
Hi @pdurbin as a part of #160, I provided a skeleton persona to start your own deployment, `prod-skel`.

Docs about it can be found at http://k8s-docs.gdcc.io/en/v4.20/day1/index.html#build-bases-and-environment-overlays
I could provide a downloadable TAR-ball for the skeleton, too, for a faster start than cloning the project from GH.

There is a new section about cloud provider usage hints, too (http://k8s-docs.gdcc.io/en/v4.20/day1/provider-hints.html). We could provide downloadable snippets there to patch for certain clouds if that's feasible. An operator #82 might also optimize for using on different clouds. 

The `ec2-create-instance.sh` is used mainly during development. There is extensive documentation about how to use this project for development purposes, using tooling like skaffold etc. http://k8s-docs.gdcc.io/en/v4.20/development/index.html Obviously this could be extended, more options can be described in more details etc. A facelift would be good, too, as the used tools were upgraded since writing the docs and matured a lot.

Do you think we can close this issue or re-shape into polishing the dev usage docs?

**Comment by pdurbin** [comment]
@poikilotherm you've written more than enough documentation to get me started. Thanks! I don't think I'll have time to work on this any time soon so I'm just going to close it.
