### ISSUE TITLE
Create a demo for using DCM

### ISSUE THREAD

**Issue by Thanh-Thanh** [GlobalDataverseCommunityConsortium/dataverse-kubernetes#68]
Hello,
It will be a great help having a demo on dataverse with DCM (data capture module). 
We can quickly test or do the demo on this functionality.

Thanks in advanced,

Thanh Thanh

**Comment by poikilotherm** [comment]
Hey @Thanh-Thanh,

thanks for opening this issue.
Do you have any experience with K8s? It would be great to have some community contribution to this, as I am currently working on #64 and #63 and others.

Cheers,
Oliver

**Comment by poikilotherm** [comment]
*Note:* on [IRC @pdurbin mentioned](http://irclog.iq.harvard.edu/dataverse/2019-10-17#i_108863) one needs to change [:FileFixityChecksumAlgorithm](http://guides.dataverse.org/en/latest/installation/config.html?highlight=md5#filefixitychecksumalgorithm) to SHA1.

**Comment by pdurbin** [comment]
I really thought I'd find some docs on this but couldn't. Maybe @pameyer knows. (He'd probably be supportive of this issue, by the way, because he's interested in DCM being more easily tested over time.) For the history on the md5/sha1 change here's the original issue, at least: https://github.com/IQSS/dataverse/issues/3354

In my mind, being able to spin up DCM next to Dataverse is part of the "Dataverse App Store" idea in https://github.com/IQSS/dataverse/issues/5688

@Thanh-Thanh I hope you've had some success with DCM! Scholars Portal is also looking into it.

**Comment by poikilotherm** [comment]
This issue is more than a year old. I'm closing this, as in the foreseeable future, my employer will not use DCM.
If you @Thanh-Thanh or someone else is keen to create an integration, docs and ideally testing, feel free to re-open and reach out.
